version: "3.8"

networks:
  cart-net:
    driver: bridge

volumes:
  mongodb_data:

services:
  cart-mongodb:
    image: mongo
    networks:
      - cart-net
    environment:
      - PUID=1000
      - PGID=1000
    volumes:
      - mongodb_data:/data/db
    ports:
      - 27017:27017
    restart: unless-stopped


  #################################
  # Cart: The Cart microservice
  #################################
  cart:
    image: carleb123/cart
    networks:
      - cart-net
    depends_on:
      - cart-mongodb
    ports:
      - 5001:5001
    restart: always

