apiVersion: v1
items:
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cart-mongodb
      name: cart-mongodb
    spec:
      ports:
        - name: "27017"
          port: 27017
          targetPort: 27017
      selector:
        io.kompose.service: cart-mongodb
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cartms
      name: cartms
    spec:
      type: LoadBalancer
      ports:
        - name: "5001"
          port: 5001
          targetPort: 5001
      selector:
        io.kompose.service: cartms
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      ports:
        - name: "1433"
          port: 1433
          targetPort: 1433
      selector:
        io.kompose.service: db
    status:
      loadBalancer: {}
  - apiVersion: v1
    kind: Service
    metadata:
      annotations:
        kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: inventoryms
      name: inventoryms
    spec:
      type: LoadBalancer
      ports:
        - name: "80"
          port: 80
          targetPort: 80
      selector:
        io.kompose.service: inventoryms
    status:
      loadBalancer: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cart-mongodb
      name: cart-mongodb
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: cart-mongodb
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.network/smartcheckout-net: "true"
            io.kompose.service: cart-mongodb
        spec:
          containers:
            - env:
                - name: PGID
                  value: "1000"
                - name: PUID
                  value: "1000"
              image: mongo
              name: cart-mongodb
              ports:
                - containerPort: 27017
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: networking.k8s.io/v1
    kind: NetworkPolicy
    metadata:
      creationTimestamp: null
      name: smartcheckout-net
    spec:
      ingress:
        - from:
            - podSelector:
                matchLabels:
                  io.kompose.network/smartcheckout-net: "true"
      podSelector:
        matchLabels:
          io.kompose.network/smartcheckout-net: "true"
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: cartms
      name: cartms
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: cartms
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.network/smartcheckout-net: "true"
            io.kompose.service: cartms
        spec:
          containers:
            - env:
                - name: PYTHONUNBUFFERED
                  value: "1"
              image: carleb12345/esd:cartms
              name: cartms
              ports:
                - containerPort: 5001
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: db
      name: db
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: db
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.network/smartcheckout-net: "true"
            io.kompose.service: db
        spec:
          containers:
            - env:
                - name: ACCEPT_EULA
                  value: "Y"
                - name: SA_PASSWORD
                  value: Password1!
              image: mcr.microsoft.com/mssql/server:latest
              name: db
              ports:
                - containerPort: 1433
              resources: {}
          restartPolicy: Always
    status: {}
  - apiVersion: apps/v1
    kind: Deployment
    metadata:
      annotations:
        kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
        kompose.version: 1.26.0 (40646f47)
      creationTimestamp: null
      labels:
        io.kompose.service: inventoryms
      name: inventoryms
    spec:
      replicas: 1
      selector:
        matchLabels:
          io.kompose.service: inventoryms
      strategy: {}
      template:
        metadata:
          annotations:
            kompose.cmd: C:\Users\caleb\Documents\kompose\kompose.exe convert -f .\docker-compose-eks.yml -o cloud-kube-eks.yaml
            kompose.version: 1.26.0 (40646f47)
          creationTimestamp: null
          labels:
            io.kompose.network/smartcheckout-net: "true"
            io.kompose.service: inventoryms
        spec:
          containers:
            - image: carleb12345/esd:inventoryms
              name: inventoryms
              ports:
                - containerPort: 80
              resources: {}
          restartPolicy: Always
    status: {}
kind: List
metadata: {}

